
{% set name = "osdatahub" %}
{% set version = "1.3.2" %}


package:
  name: { { name|lower } }
  version: { { version } }

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d09b2c7e4762c8584ed3c786f3149b0c20c25daa736d80fd3b30f2fc89889e3e

build:
  number: 1
  noarch: python
  script: { { PYTHON } } -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.10
  run:
    - geojson ~=3.2.0
    - python >=3.10
    - requests ~=2.32.4
    - shapely ~=2.1.1
    - typeguard ~=4.4.4
    - tqdm ~=4.67.1
    - urllib3 ~=2.5.0
    - zipp ~=3.23.0
test:
  imports:
    - osdatahub
    - osdatahub.FeaturesAPI
    - osdatahub.NamesAPI
    - osdatahub.PlacesAPI
about:
  home: https://github.com/OrdnanceSurvey/osdatahub
  license: OGL-UK-3.0
  license_family: OTHER
  license_file: LICENSE.txt
  summary: osdatahub is Ordnance Survey's (OS) Python API wrapper, designed to make data from the OS Data Hub APIs readily accessible to developers.
  doc_url: https://osdatahub.readthedocs.io/en/latest/
  dev_url: https://github.com/OrdnanceSurvey/osdatahub
extra:
  recipe-maintainers:
    - JEPooley
    - FHunt-OS
    - jmbraybrook